# Generated by Django 2.0.7 on 2018-07-18 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('name', models.CharField(max_length=256)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('summary', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('members', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=1024)),
                ('color_r', models.FloatField()),
                ('color_g', models.FloatField()),
                ('color_b', models.FloatField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Feedback')),
            ],
        ),
    ]
